= Ironic Container Images for OCP

== Introduction

The Ironic Containers are container images built to be distributed with Openshift Container Platform. +
They all come from the upstream https://metal3.io/[Metal3-io project], with some exceptions. +
The images currently available are:

|===
|Name of the image|Content/Purpose|Distgit

|https://github.com/openshift/ironic-image[ironic-image]|Ironic api and conductor|http://pkgs.devel.redhat.com/cgit/containers/ironic/[ironic]
|https://github.com/openshift/ironic-inspector-image/[ironic-inspector-image]|Ironic Inspector components|http://pkgs.devel.redhat.com/cgit/containers/ironic-inspector/[ironic-inspector]
|https://github.com/openshift/ironic-ipa-downloader[ironic-ipa-downloader]|Distribute the ironic python agent ramdisk|http://pkgs.devel.redhat.com/cgit/containers/ironic-ipa-downloader/[ironic-ipa-downloader]
|https://github.com/openshift/ironic-rhcos-downloader[ironic-machine-os-downloader]|Distribute the os image|http://pkgs.devel.redhat.com/cgit/containers/ironic-rhcos-downloader/[ironic-rhcos-downloader]
|https://github.com/openshift/ironic-hardware-inventory-recorder-image[ironic-hardware-inventory-recorder-image]|Ironic python agent hardware collector daemon|http://pkgs.devel.redhat.com/cgit/containers/ironic-hardware-inventory-recorder-image/[ironic-hardware-inventory-recorder-image]
|https://github.com/openshift/ironic-static-ip-manager[ironic-static-ip-manager]|Set and maintain IP for provisioning pod|http://pkgs.devel.redhat.com/cgit/containers/ironic-static-ip-manager/[ironic-static-ip-manager]
|===

All the images have been enrolled as new elements using the following documentation: +
https://docs.google.com/document/d/1SQ_qlkcplqhe8h6ONXdgBr7YUVbs4oRSj4ISl3gpLW4/edit#heading=h.78schrjzr3kg[Onboarding a new OpenShift Origin component for testing and merge automation] +
Initial work tracked in:
https://issues.redhat.com/browse/KNIDEPLOY-449[https://issues.redhat.com/browse/KNIDEPLOY-449]

To discuss new features, issues, and the project in general, has been decided to hold a meeting once every 2 weeks +
You can find more information on the recent topics of discussion https://docs.google.com/document/d/1aSiRfvWK13QoLatBObCSxDE9-PBGSMAcw389mpnxmEM/edit[here]


== Configuration Repositories

* https://github.com/openshift/release[openshift/release: Release tooling for OpenShift Origin]
This repository contains the image configuration directories, with all the images configuration files for each version we want to manage, plus master, plus the OWNERS file, auto-generated from the image repo: +
+ci-operator/config/openshift/[name-of-the-image-repository]/+ +
i.e. ci-operator/config/openshift/ironic-image/

Configuration file example: +
+openshift-ironic-image-release-4.6.yaml+ +
The workflow followed by the building process is: +
os image --> base-os image --> ironic image (the final product) +
We inject a builder in the final step (when building the real ironic image) using the “inputs” command to be able to call it in the final image with the name ironic-builder.

----
base_images:
  dev-scripts:
    name: test
    namespace: openshift-kni
    tag: dev-scripts
  os:
    name: ubi
    namespace: ocp
    tag: "8"
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.12
images:
- dockerfile_path: Dockerfile.ocp
  from: base-os
  inputs:
    base-os:
      as:
      - ironic-builder
  to: ironic
promotion:
  disabled: true
  name: "4.6"
  namespace: ocp
raw_steps:
- pipeline_image_cache_step:
    commands: |
      rm -rf /etc/yum.repos.d/*
      curl http://base-4-6-rhel8.ocp.svc > /etc/yum.repos.d/base-4-6-rhel8.repo
      curl http://base-openstack-4-6.ocp.svc > /etc/yum.repos.d/base-openstack-4-6.repo
    from: os
    to: base-os
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tag_specification:
  name: "4.6"
  namespace: ocp
tests:
- as: e2e-metal-ipi
  steps:
    cluster_profile: packet
    workflow: baremetalds-e2e
zz_generated_metadata:
  branch: release-4.6
  org: openshift
  repo: ironic-image
----

The image jobs directories contain autogenerated files that define jobs to be executed pre and post image build, plus the auto-generated OWNERS file: +
+ci-operator/jobs/openshift/[name-of-the-image-repository]/+

More info on the ci-operator can be found https://github.com/openshift/release/tree/master/ci-operator[here].

In this repository we can also find the release-controller configuration files (such as repositories):
+core-services/release-controller+

* https://github.com/openshift/ocp-build-data[openshift/ocp-build-data: Configuration data used to build OCP images]
Some important directories and files in this repo: +
images (directory that contains definitions of all images in yaml format)

group.yml (lot of configuration option for the images related to the release, for example we define synced repos here)

== Differences between Openshift upstream CI and downstream build pipeline

The upstream CI in Openshift is not a perfect reliable source to determine if the image can actually be built downstream because of substantial differences between the 2 environments.
Here’s a recap of the main differences:

* In Openshift upstream CI images can be built using any kind of source, even external sites like github and pypi, while the downstream environment is a close environment that doesn’t allow any external communication; only approved sites and repos are accessible downstream, so we need to be very careful when allowing changes upstream because they could not work downstream, effectively breaking the downstream build process.
* +++<u>+++Starting from OCP 4.6 the base image has been unified and the same image is used upstream and downstream+++</u>+++, also for intermediate layers (builders), effectively reducing the differences and enhancing the CI stream process. The ART team is working to unify base images for other older versions.
Historically (until OCP 4.5 at the moment of writing this) base images used to build the final containers were different; for example, in the upstream CI we used ubi8, adapting the image to use rhel8 repositories during build process, while downstream we directly used rhel8 as base; for a similar reason, we used different images for builders (e.g. in the ironic image), upstream we used ubi8, again with the same workaround to be able to install rhel8 packages, while downstream we used rhel8.
* Upstream CI tests only x86_64 arch, while downstream we build both x86_64 and ppc64le.
Be careful when installing components that are arch-dependent, that can break downstream build.
For example:
https://github.com/openshift/ironic-image/pull/111[https://github.com/openshift/ironic-image/pull/111]
Testing ppc64le arch based images in upstream CI is not trivial, it’s currently work in progress but there’s no ETA at the moment.

== Applying and backporting changes

==== Image Context Changes

* Always verify if we can apply patches in metal3-io image repo first. It’s better to go upstream -> downstream when applying changes.
* Apply the patch in Openshift upstream repo (master branch).
** Changes to Dockerfile must be adapted and applied to Dockerfile.ocp (or any dockerfile we use to generate the OCP images), and keeping into consideration the image configuration in the release and ocp-build-data repos if applicable.
** Changes to other files might need to be adjusted in case of substantial differences between the metal3-io image and the Openshift one.
* Verify that all the changes are downstream compatible before merge!
** Remember that downstream build process doesn’t have access to “The Internet”, so there are limitations on resources accessible. Ask to the different teams involved if a resource/package/code/site is accessible before approving a change downstream.
* Change will be fast-forwarded to the current dev branch (release-X.x, e.g if in 4.7 dev cycle, from master to release-4.7)
** Backports to older branches usually need to be accompanied with references to a Bugzilla and will require a https://docs.google.com/document/d/1PC87sSFa_zGCk95kXDW-wrVxnlgBmkHqpOgQnd4bbUw/edit[“cherry-pick-approved” label that can be applied by patch-managers only] (a rotation role that evaluates which patches need to be merged in older OCP releases). If a patch for an older release requires particular attention, it’s possible to https://docs.google.com/spreadsheets/d/1WESkYlmfNePQ_8Q8WuhdXbtzeJmjiIIBRZ2f_PaGOus/edit#gid=507763583[ping the patch-manager] in the slack channel #forum-release from Wednesday to Friday.
==== Feature Freeze

When in FF period, each change must be justified by a Bugzilla attached to the corresponding PR, and only for bugfixes. It’s not possible to apply changes that contain new features during this period, unless special circumstances arise, in which case a “feature exception” must be raised and approved.

==== Code Freeze

When in CF period, no changes can be approved and therefore merged to the current master branch. The same exception of special circumstances (usually for extremely important bugfixes or patches to secure vulnerabilities) as for FF can be applied here.


== Prepare for new release

* Make sure the configuration files in the release and ocp-build-data repos are up-to-date (this is taken care of by ART, but adjustments might be needed).
* Make sure the correct packages are tagged between releases (e.g. https://projects.engineering.redhat.com/browse/RCM-74823[https://projects.engineering.redhat.com/browse/RCM-74823])
* Make sure that all the images repositories have the correct branches created with the format release-X.x, so for example for release 4.8 there should be a release-4.8 branch (again, this should be taken care of by different teams, but please double-check).

== RPMs cross-tagging

Initial discussion and plan can be found https://docs.google.com/document/d/16gDxOr90DMLcOSRenTH8Lr9XBy5TejlJ1cSrDpvR9rQ/edit#heading=h.2k6bc85k08bk[here]. +
https://docs.google.com/drawings/d/1XR4TsgqGpRh2Jz7TlKB6BlU3DpEaGnT6iX2cf5qG-j4/edit?usp=sharing[Ironic Container Images workflow pre CI] +
https://docs.google.com/drawings/d/11CmeugBCR1hQ8fPDXmvul2tBJYw6Ev7ysW7cm21Uz4g/edit?usp=sharing[Ironic Container Images CI current workflow] (from OCP 4.6) +
All the Ironic Container Images are RPM-based container images and share packages between OSP and OCP. +
This content sharing has been discussed and approved in a specific document called https://mojo.redhat.com/docs/DOC-1202211[Shared Content Request]. +
Many ironic rpms and their dependencies come from the OSP repos, at this moment from OSP-16 and OSP-17; all the necessary packages to build the images that have been already tagged directly in OCP or cross-tagged from OSP are accessible from the following repositories:

* rhel-8-baseos
* rhel-8-appstream
* rhel-8-server-ose
All the shared rpms, when cross-tagged, can be found in the 3rd one, rhel-8-server-ose. +
Also, at this moment, to avoid double (or triple) tagging packages, the osp 16 repository has been included in all the images, although this is a temporary solution as we aim to entirely remove the dependencies from OSP repositories in the next versions. +
To achieve that, we built an “ironic product” downstream to be able to build ironic-project related packages following the upstream release schedule of ironic; currently all of the ironic projects packages and a good number of dependencies come from the tags from the ironic product.

==== Automated Validation Procedure (from OCP 4.6)

The automated validation procedure still requires some manual steps at the moment, but it’s way less complicated and less prone to errors than the manual one. The steps are as follows:

. Find which versions of packages are required to be cross-tagged and tested
A common way to do this is cross-reference the commit number of the patch we need with the naming of the package in brew; the package name contains the first 7 characters of the commit number.
For example, let’s say that we need to include the patch with commit number 0e4e00e820 from the ironic repository; we can then search in brew for the openstack-ironic package that contains the first 7 characters of the commit change number in its name, in this case 0e4e00e; our search will bring to the package +openstack-ironic-16.0.4-0.20210121171221.0e4e00e.el8 +that contains the patch we need.
At the moment the changelog list in brew doesn’t work very well so if we need to double-check the presence of the patch we’ll have to download the source rpm, extract its content using for example the rpm2cpio tool, then extract the tarball of the source and check its content. This should be fixed soon(™).
. Cross-tag the needed version of the rpm and eventually any new dependencies in the prevalidation repositories using the brew command; the correct tag depends on the OCP version, for example for OCP 4.7 use the +rhaos-4.7-rhel-8-ironic-prevalidation +tag; the actual command will then be+:+
+brew tag-build rhaos-4.7-rhel-8-ironic-prevalidation openstack-ironic-16.0.4-0.20210121171221.0e4e00e.el8+
. Wait for the sync to happen, you don’t need to do anything for this, just be patient, it usually is instantaneous but sometimes can take more time. In case you need to verify the presence of the packages in the prevalidation repo, you will need to locally clone the shared-secrets repository under the Openshift organization -> https://github.com/openshift/shared-secrets[https://github.com/openshift/shared-secrets], then use curl to browse the mirrors, for example using this command (ops-mirror.pem is a certificate in the shared-secrets repo under the mirror directory):
+curl -L -sk --cert ./ops-mirror.pem //mirror.openshift.com/enterprise/reposync/ci-ironic/rhaos-4.7-rhel-8-ironic-prevalidation/x86_64/os/Packages+
In case the new tagged packages are not present in the repo after a certain amount of time, please contact the ART Team and ask them to verify the status of the reposync jobs for the prevalidation tags/repos.
. Prepare and submit a new PR for the related image repo we need to test the new packages with (e.g. ironic-image, ironic-inspector-image, ironic-ipa-downlader are the most common) adding the versions to be tested in the main-packages-list file.
Please be extremely careful and double-check the provided RPMs info in the package brew page, sometimes the version is not what you would expect, for example in case of +openstack-ironic-16.0.4-0.20210121171221.0e4e00e.el8+ the version is +1:16.0.4-0.20210121171221.0e4e00e.el8+
. The new PR will trigger some “prevalidation” jobs which are the exact copy of the standard CI jobs but include packages from the prevalidation repos. That means that when a prevalidation job runs, it will build and test the images with the new cross-tagged packages, BUT won’t publish the image to production.
When the prevalidation jobs are green, it usually means that the new packages are safe to tag for production.
+++<u>+++The normal jobs must fail+++</u>+++, because the new packages are not present in the production repositories; if they +++<u>+++don’t+++</u>+++ fail, something’s wrong!
Verify the logs of the jobs and be sure that the installed versions are what you were expecting to be.
After verifying the status of the jobs, it’s now time to cross-tag the packages in the production repos.
. Cross-tag the packages in production using the brew command with the tag that corresponds to the OCP version needed, for example for OCP 4.7 you need to use the tag +rhaos-4.7-rhel-8-candidate+. This will add the packages to the production repo for OCP 4.7; an example of an actual command is:
+brew tag-build rhaos-4.7-rhel-8-candidate openstack-ironic-16.0.4-0.20210121171221.0e4e00e.el8+
. As in step 3, we need to wait for the sync to happen, this time for the production repository; it usually takes one hour or a little more, but sometimes can take even more time, depending on how busy the reposync jobs are.
An example command to verify the presence of the packages in the production repo is:
+curl -L -sk --cert ./ops-mirror.pem +https://use-mirror1.ops.rhcloud.com/enterprise/reposync/4.7/rhel-8-server-ose-rpms/Packages/[+https://use-mirror1.ops.rhcloud.com/enterprise/reposync/4.7/rhel-8-server-ose-rpms/Packages/]+
. Retest the PR, and this time the production and the prevalidation jobs will be green!
After the patch is merged, the image with the new RPMs will be published to production.
====
Manual Validation Procedure (deprecated, valid until OCP 4.5)

Before tagging a new package, a certain steps are required to find the correct package, verify its dependencies, and possibly check that the new package works correctly with the rest of the ensemble.+++<u>+++ A standard manual procedure (currently used up to OCP 4.6 and so deprecated)+++</u>+++, that can be also used for manual tests and troubleshooting. is composed by the following steps:

* +++<u>+++research the correct version+++</u>+++ based on various factors (usually a specific patch containing a new feature or a bug-fix)
A little trick consists in checking the name of the package, that includes the short commit version that we need to search for.
* +++<u>+++do a compatibility check+++</u>+++ cross-referencing packages related to the new one we need to tag (for example inspector and ironic-python-agent, ironic and sushy)
* +++<u>+++do a dependencies check+++</u>+++ between all the packages we need to tag and choosing the best version of the dependencies we need (usually the minimum needed version between all packages, e.g. if we need to tag 2 packages, and they both have ironic-lib as dependency, but with different versions, we need to tag the most recent one)
* +++<u>+++look for hidden dependencies+++</u>+++; this means looking for dependencies that are recommended in the packages but not required or, even worse, required in the upstream requirements but forgotten in the rpms, it could happen for example for driver clients or third-party libraries
* +++<u>+++do an installation test+++</u>+++ on a base image using the repositories that are used in the actual build process and adjust for any missing dependency (so it might result in going back to the precedent step)
* +++<u>+++do a service start test+++</u>+++ to verify that the service starts correctly and there are no hidden dependencies (this could happen with hardware drivers for example).
Ideally we should also build the container and run it using the dev-scripts testing environment to verify the functionality with the entire platform; at the moment, this is a tricky manual procedure, that requires injecting the correct repositories in the image and being under vpn to be able for the image to reach them.
The procedure to tag new versions of rpms +++<u>+++that has already been tagged in OSP and also added to an OCP list+++</u>+++ is as follows:

* If we ended to tag packages not only in the current version but also older version, please create a bug in Bugzilla to describe why a new version of the rpm is needed, and for which builds/versions of OCP; a bug in Bugzilla is also needed if we’re in any “Feature Freeze” phase.
* Create a Jira task to track the change; if a Jira task is already present, and we need to apply tags for multiple OCP versions, please reference the bug in Bugzilla in the Jira task.
A very recent example:
https://issues.redhat.com/browse/KNIDEPLOY-3036[https://issues.redhat.com/browse/KNIDEPLOY-3036]
* Cross-tag the needed version of the rpm and eventually any new dependencies using the brew command; the correct tag depends on the OCP version, for example:
+brew tag-build rhaos-4.4-rhel-8-candidate openstack-ironic-python-agent-5.0.1-0.20200123140813.025b790.el8ost.noarch.rpm+
* Verification of the newly cross-tagged package can be done in the upstream CI triggering a new build with a trivial change, or in a downstream build when available (usually every 6 hours).
* If anything should go wrong, don’t panic! It could happen that a package is available downstream first, because of how the repositories sync works between upstream and downstream. In this case just be patient and wait for the sync to happen.
+++<u>+++If there’s an issue related to the package (for example for missing dependencies), it’s always possible to untag it or just tag the dependencies with brew.+++</u>+++
If a package is NOT included in the initial Shared Content Request, a new Shared Content Request is required to handle the specific case. This will be accompanied by possibly a Jira task and a Bugzilla bug entry. +
See for example the “ipxe incident”:
https://bugzilla.redhat.com/show_bug.cgi?id=1776929[https://bugzilla.redhat.com/show_bug.cgi?id=1776929]

== Troubleshooting

This paragraph is mainly about troubleshooting errors in PRs (upstream CI) or during image build process downstream. +
In the upstream CI, there are various tests that run to verify that the image can actually be built before merging any change, for example the ci prow images jobs, that actually start a build of the image using the dockerfile specified in its configuration in the release repo. When something goes wrong in the upstream CI tests, checking the build logs will reveal what went wrong. +
The downstream build process happens automatically at different times; every time an image is built, the system will send a report to a mailing list (you could specify a list of addresses, but a mailing list is the preferred method) configured in the ocp-build-data repository, for example: https://github.com/openshift/ocp-build-data/blob/openshift-4.4/images/ironic.yml#L23[https://github.com/openshift/ocp-build-data/blob/openshift-4.4/images/ironic.yml#L23]
To receive reports on builds a user should be included in the ironic-osp-owners mailing list (mailto:ironic-osp-owners@redhat.com[ironic-osp-owners@redhat.com]). +
Reports can be of different nature:

* Successful builds from buildsys: yay! Usually they can be ignored, but they can also be useful to get information from the build, verify the versions of the packages installed, as well as if the build process is actually doing what’s expected. They contain a link to the build logs in the “Logs” line.
* Test reports from cvp-ops: these contain different verification tests, such as security, integrity and sanity checks; if something goes wrong here, it means the image builds correctly but something else is wrong, read the report carefully as the error is usually reported in red and contains a link to the test that is failing.
* Failed builds from aos-art-automation: if you receive one of these reports, it means the build process for the image failed for a reason internal to the image; it can be an error in the dockerfile, in one of the scripts in the image, a missing package, a sync issue, a configuration issue, and so on.
One very successful way to deal with these failures is to check the link to the brew build task and analyze the logs of the builds, for example:https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=26584228[https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=26584228[ ]]https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=26584228[https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=26584228]
Most of the times, issues related specifically to the images can be fixed directly by the maintainers of the images, but sometimes it could happen that issues arise not strictly related to the images themselves. In case of issues related to the content and downstream process in general, the main group to contact is the AOS ART Team (slack channel: #aos-art), while for the upstream CI platform the group to contact is the Test Platform Team (slack channel: #forum-testplatform).

== Appendix A: build your very own OCP images!

=== Build a standard image

While images from the Metal3-io project can be built directly locally as they are in the repositories, the images for Openshift can’t. +
This is due mainly to the fact that the build process use mechanisms and repositories that are not available to the final user, so some changes are required to be able to build them:

* Make sure to be under the Red Hat vpn or on a machine that can reach the Red Hat internal network to be able to reach the internal repositories
* Prepare a .repo file that contains all the necessary repositories inside the image directory, based on the OCP version needed. For example, for OCP 4.6 the repositories are:
----
[rhel-8-appstream-rpms-x86_64]
baseurl = http://pulp.dist.prod.ext.phx2.redhat.com/content/dist/rhel8/8/x86_64/appstream/os/
name = rhel-8-appstream-rpms-x86_64
enabled = 1
gpgcheck = 0

[rhel-8-baseos-rpms-x86_64]
baseurl = http://pulp.dist.prod.ext.phx2.redhat.com/content/dist/rhel8/8/x86_64/baseos/os/
name = rhel-8-baseos-rpms-x86_64
enabled = 1
gpgcheck = 0

# adapt based on version so 4.6 will be 4.6-el8
[rhel-8-server-ose-rpms-x86_64]
baseurl = http://download.lab.bos.redhat.com/rcm-guest/puddles/RHAOS/AtomicOpenShift/4.6-el8/latest/x86_64/os
name = rhel-8-server-ose-rpms-x86_64
enabled = 1
gpgcheck = 0

[openstack-16-for-rhel-8-rpms-x86_64]
baseurl = http://pulp.dist.prod.ext.phx2.redhat.com/content/dist/layered/rhel8/x86_64/openstack/16/os/
enabled = 1
name = openstack-16-for-rhel-8-rpms-x86_64
gpgcheck = 0
gpgkey = file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
----
* For each image we want to build:
** Open the dockerfile.ocp
** Check if it makes use of a “builder” layer, for example the ironic-image has this line on top: +FROM ironic-builder AS builder+
*** Change that to: +FROM ubi8 as builder+
** After each +FROM+ entry in the dockerfile.ocp insert the commands to provide the new repositories, for example if you called your .repo file “ocp46.repo” you would insert:
RUN +rm -f /etc/yum.repos.d/*
COPY +ocp46.repo+ /etc/yum.repos.d/+
** This should suffice, you can now save and exit from dockerfile.ocp and run:
+podman build -f Dockerfile.ocp+
=== Build with new packages

Sometimes we’d like to build a local image using new packages that have to be tagged yet, especially if we want to test a new version of a package in a development environment. +
To do that, we need to add the installation of the package from a local source or, if we know the remote path, directly from brew or another url (remember that only internal urls are reachable from the build infrastructure, so plan for that!):

* After preparing the image for the local build, as explained before in “Build a standard image”, we can append the new versions of the files we want to install to the +main-packages-list.txt+ file, that contains the base list of the packages installed in the image, as urls.
For example, if we want to install a new version of ironic, we can search for *openstack-ironic* in brew, open one of the recent versions, for example openstack-ironic-15.2.1-0.20200826161928.99e8fc9.el8ost, then check the list of associated rpms, in this case:
** openstack-ironic-api-15.2.1-0.20200826161928.99e8fc9.el8ost.noarch.rpm
** openstack-ironic-common-15.2.1-0.20200826161928.99e8fc9.el8ost.noarch.rpm
** openstack-ironic-conductor-15.2.1-0.20200826161928.99e8fc9.el8ost.noarch.rpm
For each of them, copy the download link inside the main-packages-list.txt

* Run:
+podman build -f Dockerfile.ocp+
* Sometimes new dependencies will be required; in this case make sure they’re available in brew, do the same process to add the urls to the+ main-packages-list.txt+ and run the podman build command again, until all the dependencies are satisfied
* Once the build process completes, you’ll have a new image ready with new packages, that can be tested with dev-scripts.
== Appendix B: Real World Examples - from patch to release (prior to OCP 4.7)

This section will walk through specific ironic* patches and the steps necessary to take an upstream ironic* patch into an OCP release.

=== Ironic fix into OCP 4.5

. OCP bug https://bugzilla.redhat.com/show_bug.cgi?id=1828885[https://bugzilla.redhat.com/show_bug.cgi?id=1828885] created from field tests
. Upstream patch https://review.opendev.org/#/c/725239/[https://review.opendev.org/#/c/725239/] merged to master
. Upstream patch cherry-picked to stable/trainhttps://review.opendev.org/#/c/727906/[ https://review.opendev.org/#/c/727906/]
. OSP bug https://bugzilla.redhat.com/show_bug.cgi?id=1841216[https://bugzilla.redhat.com/show_bug.cgi?id=1841216] cloned from OCP bug, targeted to OSP 16.1
. Downstream patch https://code.engineering.redhat.com/gerrit/#/c/201684/[https://code.engineering.redhat.com/gerrit/#/c/201684/] created via backport to rhos-16.1-trunk-patches
. openstack-ironic pkg manually built - https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=1217308[https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=1217308] using procedure here http://etherpad.corp.redhat.com/lwB9V4BBu6[http://etherpad.corp.redhat.com/lwB9V4BBu6]
. openstack-ironic pkg tagged by Riccardo with rhaos-4.5-rhel-8-candidate tag using command as described above e.g.:
.. “brew tag-build rhaos-4.5-rhel-8-candidate openstack-ironic-13.0.4-0.20200529150916.911bc51.el8ost”
. The openstack-ironic pkg is synced to the repo downstream, then mirrored upstream (in Openshift) so upstream Openshift CI gets the package after its available downstream
. OCP bug https://bugzilla.redhat.com/show_bug.cgi?id=1828885[https://bugzilla.redhat.com/show_bug.cgi?id=1828885] merged to ON_QA manually since there is no openshift PR to do it automatically
.. To confirm that the pkg is in a build go to https://brewweb.engineering.redhat.com/brew/search[https://brewweb.engineering.redhat.com/brew/search] and search for ironic-container and look for the latest build with -v4.5.  Go to the bottom of the page and use “x86_64-build.log” link, then search for “openstack-ironic” and compare that to the expected ironic pkg.  (Note - old builds are cleaned out so particular builds may be removed)

=== Ironic fix into OCP 4.6 (deprecated)

Note that this process is slightly different since 4.6 is using the upstream master branch, e.g. Victoria

. Upstream patch https://review.opendev.org/#/c/739779/[https://review.opendev.org/#/c/739779/] merged to master
. Downstream package for OSP 17 will be built and will include this fix
.. For everything that is not a library, e.g. ironic, ironic-inspector, ipa etc., will be built automatically from master without a new release and can be seen in brew
.. For libraries, e.g. python3-sushy an upstream release is required in order for the change to be picked up, for example - https://review.opendev.org/#/c/748214/[https://review.opendev.org/#/c/748214/]
. OCP 4.6 bug created to tag Ironic pkg - https://bugzilla.redhat.com/show_bug.cgi?id=1869183[https://bugzilla.redhat.com/show_bug.cgi?id=1869183]
. Package https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=1266093[https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=1266093] tagged with 4.6 candidate tag using
.. “brew tag-build rhaos-4.6-rhel-8-candidate openstack-ironic-15.1.1-0.20200724075308.3e92fd0.el8ost”
. The openstack-ironic pkg is synced to the repo downstream, then mirrored upstream (in Openshift) so upstream Openshift CI gets the package after its available downstream
. Verified https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=1276451[https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=1276451] has ironic-api 15.1.1-0.20200724075308.3e92fd0.el8ost in build log
=== Ironic-python-agent into OCP 4.6 (deprecated)

Note that this procedure is deprecated in favor of installing ironic-images from the ironic product and removed in OCP 4.7

. OCP bug https://bugzilla.redhat.com/show_bug.cgi?id=1867744[https://bugzilla.redhat.com/show_bug.cgi?id=1867744] created from internal test
. Julia posted patch upstream to ironic-python-agent https://review.opendev.org/#/c/747072/[https://review.opendev.org/#/c/747072/]
. After 1 day the pkg was built https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=1308838[https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=1308838].  Can verify that the patch is in the ChangeLog and pkg is tagged for _rhos-17.0-rhel-8-trunk-candidate_
. Test this package by following the method in Appendix C:
.. Set this in config_stack.sh
... export IRONIC_IPA_DOWNLOADER_LOCAL_IMAGE=https://github.com/openshift/ironic-ipa-downloader
... export IRONIC_IPA_DOWNLOADER_DOCKERFILE=Dockerfile.ocp
... export CUSTOM_REPO_FILE=ocp46.repo
.. Set up main-packages-list.txt as follows (copy download link from pkg in brew)
$ cat ironic-ipa-downloader/main-packages-list.txt +
http://download.eng.bos.redhat.com/brewroot/vol/rhel-8/packages/openstack-ironic-python-agent/6.3.1/0.20200904042948.e73b722.el8ost/noarch/openstack-ironic-python-agent-6.3.1-0.20200904042948.e73b722.el8ost.noarch.rpm[http://download.eng.bos.redhat.com/brewroot/vol/rhel-8/packages/openstack-ironic-python-agent/6.3.1/0.20200904042948.e73b722.el8ost/noarch/openstack-ironic-python-agent-6.3.1-0.20200904042948.e73b722.el8ost.noarch.rpm] +
http://download.eng.bos.redhat.com/brewroot/vol/rhel-8/packages/openstack-ironic-python-agent/6.3.1/0.20200904042948.e73b722.el8ost/noarch/python3-ironic-python-agent-6.3.1-0.20200904042948.e73b722.el8ost.noarch.rpm[http://download.eng.bos.redhat.com/brewroot/vol/rhel-8/packages/openstack-ironic-python-agent/6.3.1/0.20200904042948.e73b722.el8ost/noarch/python3-ironic-python-agent-6.3.1-0.20200904042948.e73b722.el8ost.noarch.rpm] +
 	python3-ironic-lib

. Created a bug to tag the package - https://bugzilla.redhat.com/show_bug.cgi?id=1875510[https://bugzilla.redhat.com/show_bug.cgi?id=1875510]
. Once package is verified, tag it with “brew tag-build rhaos-4.6-rhel-8-candidate openstack-ironic-python-agent-6.3.1-0.20200904042948.e73b722.el8ost”
. Can check that the next ironic-ipa-downloader-container that was built (e.g. https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=1313535[https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=1313535]) has the openstack-ironic-python-agent rpm
Ironic-python-agent in OCP 4.7 and forward

== Appendix C: Test with dev-scripts and custom images

The CI that tests all the changes for the ironic images and in general for IPI uses dev-scripts to validate them. +
A convenient way to test the images, for example before tagging new packages, is using dev-scripts with custom images. +
To build custom images while running dev-scripts, you can follow the instructions in this video:
https://drive.google.com/file/d/1KGLbfQvYHQmcqe2zCtQz0cCaebSTXdQV/view?usp=sharing[https://drive.google.com/file/d/1KGLbfQvYhttps://github.com/metal3-io/ironic-image/pull/56https://github.com/metal3-io/ironic-image/pull/56HQmcqe2zCtQz0cCaebSTXdQV/view?usp=sharing] +
At the moment, it’s not possible yet to use custom list of packages (work in progress) in an automated way, but with some manual changes that can be accomplished anyway:

* Clone the image repo you need to customize under your user dir, for example for ironic-image:
+git clone https://github.com/openshift/ironic-image+
* Inside the cloned repository, modify the +main-packages-list.txt+ as explained in Appendix A to include the urls of the rpms included in the packages you need to test
* Follow the configuration steps to run dev-scripts with a custom image as explained in the video above
* Run dev-scripts!
== Appendix D: FAQ

* How can I determine which images versions an OCP build is using?
Using the oc command is possible to get a lot of information on OCP builds, like all the component image pullspecs.
For example, let’s consider a dev preview underhttp://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp-dev-preview/[http://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp-dev-preview/[ ]]http://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp-dev-preview/[http://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp-dev-preview/], like:

+nightly=4.7.0-0.nightly-2020-11-18-085225+
+oc adm release info --pullspecs quay.io/openshift-release-dev/ocp-release-nightly:$nightly+ +
# or for a specific component: +
----
oc adm release info --image-for ironic quay.io/openshift-release-dev/ocp-release-nightly:$nightly

----
All the info are public, but you still need to be authenticated on quay.io registry with a valid pull secret.
Go to https://cloud.redhat.com/openshift/install/crc/installer-provisioned[https://cloud.redhat.com/openshift/install/crc/installer-provisioned] and download the pull secret from there or just use the one used to test dev-scripts contained in pull_secret.json; for example, assuming that can be found in the dev-scripts dir:
+registry=/home/$USER/dev-scripts/pull_secret.json+ +
+oc image info $(oc adm release info --image-for ironic+http://quay.io/openshift-release-dev/ocp-release-nightly:$nightly[http://quay.io/openshift-release-dev/ocp-release-nightly:$nightly[+ ]]+http://quay.io/openshift-release-dev/ocp-release-nightly:$nightly[+quay.io/openshift-release-dev/ocp-release-nightly:$nightly]++ --registry-config=$registry) --registry-config=$registry+ +
Will provide the NVR that can be found in brew, or directly asking to @art-bot on slack.
For example:
@art-bot which build of ironic is in 4.7.0-0.nightly-2020-11-18-085225 +
art-bot: 4.7.0-0.nightly-2020-11-18-085225 ironic image (pullspec) came from brew build ironic-container-v4.7.0-202011171907.p0 from commit 1cbb9035 +
@art-bot which rpms glibc,openstack-ironic-common are in image ironic-container-v4.7.0-202011171907.p0 +
art-bot: The following rpm(s) are used in ironic-container-v4.7.0-202011171907.p0 +
ironic-container-v4.7.0-202011171907.p0-rpms +
glibc-2.28-127.el8.ppc64le +
glibc-2.28-127.el8.x86_64 +
openstack-ironic-common-16.0.2-0.20201105091209.193b93c.el8.noarch

* When is an image built/rebuilt?
Automatic ART rebuilds:
** upstream source code change
** base image changed
** rpm installed in final image has a newly tagged version
If the RPM is not installed in the final image and is just used to support a stage in a multi-stage docker build, then the package must be explicitly called out in the ART metadata.
If any of that does not get you an automated rebuild, then just ask ART to manually kick off a rebuild of specific image(s).
* What if I need to rebuild an ironic-python-agent ramdisk?
Thanks Lon for this:
https://docs.engineering.redhat.com/pages/viewpage.action?pageId=173283121[https://docs.engineering.redhat.com/pages/viewpage.action?pageId=173283121]

== Appendix E: Versions Audit

OCP 4.6.15 +
https://docs.google.com/document/d/1TQO-VwWQuOpdEEiwEJzzT_giDq0-4n8zeWxh8FxC3RQ/edit?usp=sharing[https://docs.google.com/document/d/1TQO-VwWQuOpdEEiwEJzzT_giDq0-4n8zeWxh8FxC3RQ/edit?usp=sharing]

OCP 4.7.0 +
https://docs.google.com/document/d/156iYc3DrDUvN4eXEakVccjtDaOK39bBlyUBCbw7vknc/edit?usp=sharing[https://docs.google.com/document/d/156iYc3DrDUvN4eXEakVccjtDaOK39bBlyUBCbw7vknc/edit?usp=sharing]


