= Ironic Container Images for OCP test

:toc:
:homepage: https://example.org

== Introduction

The Ironic Containers are container images built to be distributed with Openshift Container Platform. +
They all come from the upstream https://metal3.io/[Metal3-io project], with some exceptions. +
The images currently available are:

|===
|Name of the image|Content/Purpose|Distgit

|https://github.com/openshift/ironic-image[ironic-image]|Ironic api and conductor|http://pkgs.devel.redhat.com/cgit/containers/ironic/[ironic]
|https://github.com/openshift/ironic-inspector-image/[ironic-inspector-image]|Ironic Inspector components|http://pkgs.devel.redhat.com/cgit/containers/ironic-inspector/[ironic-inspector]
|https://github.com/openshift/ironic-ipa-downloader[ironic-ipa-downloader]|Distribute the ironic python agent ramdisk|http://pkgs.devel.redhat.com/cgit/containers/ironic-ipa-downloader/[ironic-ipa-downloader]
|https://github.com/openshift/ironic-rhcos-downloader[ironic-machine-os-downloader]|Distribute the os image|http://pkgs.devel.redhat.com/cgit/containers/ironic-rhcos-downloader/[ironic-rhcos-downloader]
|https://github.com/openshift/ironic-hardware-inventory-recorder-image[ironic-hardware-inventory-recorder-image]|Ironic python agent hardware collector daemon|http://pkgs.devel.redhat.com/cgit/containers/ironic-hardware-inventory-recorder-image/[ironic-hardware-inventory-recorder-image]
|https://github.com/openshift/ironic-static-ip-manager[ironic-static-ip-manager]|Set and maintain IP for provisioning pod|http://pkgs.devel.redhat.com/cgit/containers/ironic-static-ip-manager/[ironic-static-ip-manager]
|===

All the images have been enrolled as new elements using the following documentation: +
https://docs.google.com/document/d/1SQ_qlkcplqhe8h6ONXdgBr7YUVbs4oRSj4ISl3gpLW4/edit#heading=h.78schrjzr3kg[Onboarding a new OpenShift Origin component for testing and merge automation] +
Initial work tracked in:
https://issues.redhat.com/browse/KNIDEPLOY-449[https://issues.redhat.com/browse/KNIDEPLOY-449]

To discuss new features, issues, and the project in general, has been decided to hold a meeting once every 2 weeks +
You can find more information on the recent topics of discussion https://docs.google.com/document/d/1aSiRfvWK13QoLatBObCSxDE9-PBGSMAcw389mpnxmEM/edit[here]


== Configuration Repositories

* https://github.com/openshift/release[openshift/release: Release tooling for OpenShift Origin]
This repository contains the image configuration directories, with all the images configuration files for each version we want to manage, plus master, plus the OWNERS file, auto-generated from the image repo: +
+ci-operator/config/openshift/[name-of-the-image-repository]/+ +
i.e. ci-operator/config/openshift/ironic-image/

Configuration file example: +
+openshift-ironic-image-release-4.6.yaml+ +
The workflow followed by the building process is: +
os image --> base-os image --> ironic image (the final product) +
We inject a builder in the final step (when building the real ironic image) using the “inputs” command to be able to call it in the final image with the name ironic-builder.

----
base_images:
  dev-scripts:
    name: test
    namespace: openshift-kni
    tag: dev-scripts
  os:
    name: ubi
    namespace: ocp
    tag: "8"
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.12
images:
- dockerfile_path: Dockerfile.ocp
  from: base-os
  inputs:
    base-os:
      as:
      - ironic-builder
  to: ironic
promotion:
  disabled: true
  name: "4.6"
  namespace: ocp
raw_steps:
- pipeline_image_cache_step:
    commands: |
      rm -rf /etc/yum.repos.d/*
      curl http://base-4-6-rhel8.ocp.svc > /etc/yum.repos.d/base-4-6-rhel8.repo
      curl http://base-openstack-4-6.ocp.svc > /etc/yum.repos.d/base-openstack-4-6.repo
    from: os
    to: base-os
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tag_specification:
  name: "4.6"
  namespace: ocp
tests:
- as: e2e-metal-ipi
  steps:
    cluster_profile: packet
    workflow: baremetalds-e2e
zz_generated_metadata:
  branch: release-4.6
  org: openshift
  repo: ironic-image
----
