= Ironic Container Images for OCP

== Ironic Asciidoc demo

The Ironic Containers are container images built to be distributed with Openshift Container Platform. +
They all come from the upstream https://metal3.io/[Metal3-io project], with some exceptions. +
The images currently available are:

|===
|Name of the image|Content/Purpose|Distgit

|https://github.com/openshift/ironic-image[ironic-image]|Ironic api and conductor|http://pkgs.devel.redhat.com/cgit/containers/ironic/[ironic]
|https://github.com/openshift/ironic-inspector-image/[ironic-inspector-image]|Ironic Inspector components|http://pkgs.devel.redhat.com/cgit/containers/ironic-inspector/[ironic-inspector]
|https://github.com/openshift/ironic-ipa-downloader[ironic-ipa-downloader]|Distribute the ironic python agent ramdisk|http://pkgs.devel.redhat.com/cgit/containers/ironic-ipa-downloader/[ironic-ipa-downloader]
|https://github.com/openshift/ironic-rhcos-downloader[ironic-machine-os-downloader]|Distribute the os image|http://pkgs.devel.redhat.com/cgit/containers/ironic-rhcos-downloader/[ironic-rhcos-downloader]
|https://github.com/openshift/ironic-hardware-inventory-recorder-image[ironic-hardware-inventory-recorder-image]|Ironic python agent hardware collector daemon|http://pkgs.devel.redhat.com/cgit/containers/ironic-hardware-inventory-recorder-image/[ironic-hardware-inventory-recorder-image]
|https://github.com/openshift/ironic-static-ip-manager[ironic-static-ip-manager]|Set and maintain IP for provisioning pod|http://pkgs.devel.redhat.com/cgit/containers/ironic-static-ip-manager/[ironic-static-ip-manager]
|===

All the images have been enrolled as new elements using the following documentation: +
https://docs.google.com/document/d/1SQ_qlkcplqhe8h6ONXdgBr7YUVbs4oRSj4ISl3gpLW4/edit#heading=h.78schrjzr3kg[Onboarding a new OpenShift Origin component for testing and merge automation] +
Initial work tracked in:
https://issues.redhat.com/browse/KNIDEPLOY-449[https://issues.redhat.com/browse/KNIDEPLOY-449]

To discuss new features, issues, and the project in general, has been decided to hold a meeting once every 2 weeks +
You can find more information on the recent topics of discussion https://docs.google.com/document/d/1aSiRfvWK13QoLatBObCSxDE9-PBGSMAcw389mpnxmEM/edit[here]


== Configuration Repositories

* https://github.com/openshift/release[openshift/release: Release tooling for OpenShift Origin]
This repository contains the image configuration directories, with all the images configuration files for each version we want to manage, plus master, plus the OWNERS file, auto-generated from the image repo: +
+ci-operator/config/openshift/[name-of-the-image-repository]/+ +
i.e. ci-operator/config/openshift/ironic-image/

Configuration file example: +
+openshift-ironic-image-release-4.6.yaml+ +
The workflow followed by the building process is: +
os image --> base-os image --> ironic image (the final product) +
We inject a builder in the final step (when building the real ironic image) using the “inputs” command to be able to call it in the final image with the name ironic-builder.

----
base_images:
  dev-scripts:
    name: test
    namespace: openshift-kni
    tag: dev-scripts
  os:
    name: ubi
    namespace: ocp
    tag: "8"
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.12
images:
- dockerfile_path: Dockerfile.ocp
  from: base-os
  inputs:
    base-os:
      as:
      - ironic-builder
  to: ironic
promotion:
  disabled: true
  name: "4.6"
  namespace: ocp
raw_steps:
- pipeline_image_cache_step:
    commands: |
      rm -rf /etc/yum.repos.d/*
      curl http://base-4-6-rhel8.ocp.svc > /etc/yum.repos.d/base-4-6-rhel8.repo
      curl http://base-openstack-4-6.ocp.svc > /etc/yum.repos.d/base-openstack-4-6.repo
    from: os
    to: base-os
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tag_specification:
  name: "4.6"
  namespace: ocp
tests:
- as: e2e-metal-ipi
  steps:
    cluster_profile: packet
    workflow: baremetalds-e2e
zz_generated_metadata:
  branch: release-4.6
  org: openshift
  repo: ironic-image
----

The image jobs directories contain autogenerated files that define jobs to be executed pre and post image build, plus the auto-generated OWNERS file: +
+ci-operator/jobs/openshift/[name-of-the-image-repository]/+

More info on the ci-operator can be found https://github.com/openshift/release/tree/master/ci-operator[here].

In this repository we can also find the release-controller configuration files (such as repositories):
+core-services/release-controller+

* https://github.com/openshift/ocp-build-data[openshift/ocp-build-data: Configuration data used to build OCP images]
Some important directories and files in this repo: +
images (directory that contains definitions of all images in yaml format)

group.yml (lot of configuration option for the images related to the release, for example we define synced repos here)

== Differences between Openshift upstream CI and downstream build pipeline

The upstream CI in Openshift is not a perfect reliable source to determine if the image can actually be built downstream because of substantial differences between the 2 environments.
Here’s a recap of the main differences:

* In Openshift upstream CI images can be built using any kind of source, even external sites like github and pypi, while the downstream environment is a close environment that doesn’t allow any external communication; only approved sites and repos are accessible downstream, so we need to be very careful when allowing changes upstream because they could not work downstream, effectively breaking the downstream build process.
* +++<u>+++Starting from OCP 4.6 the base image has been unified and the same image is used upstream and downstream+++</u>+++, also for intermediate layers (builders), effectively reducing the differences and enhancing the CI stream process. The ART team is working to unify base images for other older versions.
Historically (until OCP 4.5 at the moment of writing this) base images used to build the final containers were different; for example, in the upstream CI we used ubi8, adapting the image to use rhel8 repositories during build process, while downstream we directly used rhel8 as base; for a similar reason, we used different images for builders (e.g. in the ironic image), upstream we used ubi8, again with the same workaround to be able to install rhel8 packages, while downstream we used rhel8.
* Upstream CI tests only x86_64 arch, while downstream we build both x86_64 and ppc64le.
Be careful when installing components that are arch-dependent, that can break downstream build.
For example:
https://github.com/openshift/ironic-image/pull/111[https://github.com/openshift/ironic-image/pull/111]
Testing ppc64le arch based images in upstream CI is not trivial, it’s currently work in progress but there’s no ETA at the moment.

== Applying and backporting changes

==== Image Context Changes

* Always verify if we can apply patches in metal3-io image repo first. It’s better to go upstream -> downstream when applying changes.
* Apply the patch in Openshift upstream repo (master branch).
** Changes to Dockerfile must be adapted and applied to Dockerfile.ocp (or any dockerfile we use to generate the OCP images), and keeping into consideration the image configuration in the release and ocp-build-data repos if applicable.
** Changes to other files might need to be adjusted in case of substantial differences between the metal3-io image and the Openshift one.
* Verify that all the changes are downstream compatible before merge!
** Remember that downstream build process doesn’t have access to “The Internet”, so there are limitations on resources accessible. Ask to the different teams involved if a resource/package/code/site is accessible before approving a change downstream.
* Change will be fast-forwarded to the current dev branch (release-X.x, e.g if in 4.7 dev cycle, from master to release-4.7)
** Backports to older branches usually need to be accompanied with references to a Bugzilla and will require a https://docs.google.com/document/d/1PC87sSFa_zGCk95kXDW-wrVxnlgBmkHqpOgQnd4bbUw/edit[“cherry-pick-approved” label that can be applied by patch-managers only] (a rotation role that evaluates which patches need to be merged in older OCP releases). If a patch for an older release requires particular attention, it’s possible to https://docs.google.com/spreadsheets/d/1WESkYlmfNePQ_8Q8WuhdXbtzeJmjiIIBRZ2f_PaGOus/edit#gid=507763583[ping the patch-manager] in the slack channel #forum-release from Wednesday to Friday.
